version: '3'
services:
#mssql docker
  put387-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - put387net

  put387-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:Put387ConnectionString=Server=put387-sql,1433;Database=170016;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 64904:80
    networks:
      - put387net
    links:
      - put387-sql
    depends_on:
      - put387-sql
      
networks:
  put387net:
    driver: bridge  